name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Super-Goose
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the sections below to help us fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part is affected?
      options:
        - CLI
        - Desktop App
        - Super-Goose Evolution (EvoAgentX)
        - Super-Goose Adversarial (Coach/Player)
        - Super-Goose Team (ALMAS)
        - Workflows/CI
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug
      placeholder: When I do X, Y happens, but I expected Z
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run command `goose ...`
        2. Open desktop app
        3. Click on X
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: I expected the command to succeed
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Relevant error messages or logs
      render: shell
      placeholder: |
        Paste error output here

  - type: input
    id: version
    attributes:
      label: Version
      description: Version from `goose --version`
      placeholder: v1.23.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 10
        - Windows 11
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (Ubuntu/Debian)
        - Linux (Other)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: This started happening after...
