name: ✨ Feature Request
description: Suggest a new feature or enhancement for Super-Goose
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below to help us understand your request.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part should this feature be added to?
      options:
        - CLI
        - Desktop App
        - Super-Goose Evolution (EvoAgentX)
        - Super-Goose Adversarial (Coach/Player)
        - Super-Goose Team (ALMAS)
        - Providers (LLM integrations)
        - Workflows/CI
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm trying to do X, but currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        Add a new command/option that...
        The UI should show...
        The behavior should be...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you thought about?
      placeholder: |
        I considered doing X instead, but...
        Other tools solve this by...

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Links to similar features in other tools
      placeholder: |
        Tool X has this feature: https://...
        Example use case: ...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Blocking my adoption
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help test this feature
        - label: I can help document this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots
      placeholder: This would help with...
