name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to build (branch, tag, or SHA)'
        required: false
        default: 'main'
        type: string
      push_to_registry:
        description: 'Push to Docker Hub'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: inputs.push_to_registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ inputs.push_to_registry }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Save Docker image as tar
        if: "!inputs.push_to_registry"
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag goose:latest \
            --load \
            .
          docker save goose:latest | gzip > goose-docker-amd64.tar.gz

      - name: Upload Docker image artifact
        if: "!inputs.push_to_registry"
        uses: actions/upload-artifact@v4
        with:
          name: goose-docker-image
          path: goose-docker-amd64.tar.gz

      - name: Upload to release if tag exists
        if: startsWith(github.ref, 'refs/tags/') && !inputs.push_to_registry
        uses: softprops/action-gh-release@v1
        with:
          files: goose-docker-amd64.tar.gz
          tag_name: ${{ github.ref_name }}
