name: Build Windows Desktop (Unsigned)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to build (branch, tag, or SHA)'
        required: false
        default: 'main'
        type: string

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        working-directory: ui/desktop
        run: npm ci

      - name: Build Rust FFI
        run: cargo build --release --package goose-ffi

      - name: Copy FFI DLL
        run: |
          New-Item -ItemType Directory -Force -Path ui/desktop/src/bin
          Copy-Item target/release/goose_ffi.dll ui/desktop/src/bin/

      - name: Package Windows app
        working-directory: ui/desktop
        run: npm run package

      - name: Create installer
        working-directory: ui/desktop
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: goose-windows-unsigned
          path: ui/desktop/out/make/**/*.exe

      - name: Get version
        id: version
        run: |
          $version = (Get-Content ui/desktop/package.json | ConvertFrom-Json).version
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Upload to release if tag exists
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ui/desktop/out/make/**/*.exe
          tag_name: ${{ github.ref_name }}
