name: Sync with upstream block/goose

on:
  schedule:
    # Run weekly on Sunday at 3 AM UTC (reduced from daily to prevent spam)
    - cron: '0 3 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/block/goose.git || true
          git remote -v

      - name: Fetch upstream
        run: git fetch upstream main

      - name: Check for updates
        id: check
        run: |
          BEHIND=$(git rev-list --count HEAD..upstream/main)
          echo "behind=$BEHIND" >> $GITHUB_OUTPUT
          echo "Fork is $BEHIND commits behind upstream"

      - name: Merge upstream changes
        if: steps.check.outputs.behind != '0'
        run: |
          git merge upstream/main --no-edit || {
            echo "Merge conflict detected!"
            git merge --abort
            exit 1
          }

      - name: Push changes
        if: steps.check.outputs.behind != '0'
        run: git push origin main

      - name: Create issue on conflict
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'sync,merge-conflict'
            });
            
            if (issues.data.length > 0) {
              console.log('Sync conflict issue already exists, skipping creation');
              return;
            }
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Auto-sync with upstream failed - Manual merge required',
              body: `The automatic sync with upstream \`block/goose\` failed due to merge conflicts.

              **Action Required**: Manual merge needed

              \`\`\`bash
              git fetch block main
              git merge block/main
              # Resolve conflicts manually
              git push origin main
              \`\`\`

              **Sync Details**:
              - Workflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
              - Triggered: ${{ github.event_name }}
              - Time: ${{ github.event.repository.pushed_at }}
              `,
              labels: ['sync', 'merge-conflict', 'needs-attention']
            })
